// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerAPI.data.migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20200317044902_M10")]
    partial class M10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2Library.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaOfSpecialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityOfResidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceOfResidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "a5ab360d-f299-4c26-8777-a5e08f4ac4d6",
                            AreaOfSpecialization = "Plumber",
                            CityOfResidence = "Surrey",
                            Email = "TomDay@gmail.com",
                            Employer = "Super Plumber",
                            FirstName = "Tom",
                            LastName = "Day",
                            MobileNumber = "778-554-2322",
                            ProvinceOfResidence = "BC"
                        },
                        new
                        {
                            SpeakerId = "2cbba902-cdd4-402e-80bc-9494137ab3cf",
                            AreaOfSpecialization = "Construction",
                            CityOfResidence = "Surrey",
                            Email = "JohnFox@gmail.com",
                            Employer = "JF Construction",
                            FirstName = "John",
                            LastName = "Fox",
                            MobileNumber = "778-554-2888",
                            ProvinceOfResidence = "BC"
                        },
                        new
                        {
                            SpeakerId = "5290943c-ea01-4afa-964b-dacf6f5b8eb3",
                            AreaOfSpecialization = "Waitress",
                            CityOfResidence = "Surrey",
                            Email = "ArtAsh@gmail.com",
                            Employer = "Cactus Club",
                            FirstName = "Art",
                            LastName = "Ash",
                            MobileNumber = "778-554-4444",
                            ProvinceOfResidence = "BC"
                        },
                        new
                        {
                            SpeakerId = "b2a532cd-4378-4754-9ad2-f5f817b75915",
                            AreaOfSpecialization = "Technician",
                            CityOfResidence = "Surrey",
                            Email = "HiaMia@gmail.com",
                            Employer = "Yessir",
                            FirstName = "Mia",
                            LastName = "Hay",
                            MobileNumber = "778-554-7777",
                            ProvinceOfResidence = "BC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
