// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerAPI.data.migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20200317005723_M8")]
    partial class M8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2Library.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "eabfe4eb-3cd3-4db7-9026-16b84ad557e1",
                            FirstName = "Tom",
                            LastName = "Day"
                        },
                        new
                        {
                            SpeakerId = "55468490-e851-4276-9d5f-23eac9ff9576",
                            FirstName = "John",
                            LastName = "Fox"
                        },
                        new
                        {
                            SpeakerId = "863c341c-f97f-425e-bbb9-0311864c5620",
                            FirstName = "Art",
                            LastName = "Ash"
                        },
                        new
                        {
                            SpeakerId = "a1ab19f4-dea6-4275-a057-2611a915ec85",
                            FirstName = "Mia",
                            LastName = "Hay"
                        },
                        new
                        {
                            SpeakerId = "af98e926-3654-45a3-9825-ca84ee7c3321",
                            FirstName = "Xam",
                            LastName = "Xyllene"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
