// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerAPI.data.migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20200317003938_M7")]
    partial class M7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2Library.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "c5d5ffff-9c58-4cb8-ac7c-0211aa7bcf9e",
                            FirstName = "Tom",
                            LastName = "Day"
                        },
                        new
                        {
                            SpeakerId = "5750ffae-c8bb-4dcb-b468-d0f503e3762f",
                            FirstName = "John",
                            LastName = "Fox"
                        },
                        new
                        {
                            SpeakerId = "dc7f6f4d-7f10-4cf4-8681-1ee32e8476ea",
                            FirstName = "Art",
                            LastName = "Ash"
                        },
                        new
                        {
                            SpeakerId = "6069ec86-3442-48e8-9767-d4d859a57211",
                            FirstName = "Mia",
                            LastName = "Hay"
                        },
                        new
                        {
                            SpeakerId = "69ac8727-2713-4d9d-9bb5-de9d7758bb8a",
                            FirstName = "Xam",
                            LastName = "Xyllene"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
