// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerAPI.data.migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20200317010909_M9")]
    partial class M9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2Library.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "b294819d-17f5-4ff7-afd9-b73499fe52df",
                            FirstName = "Tom",
                            LastName = "Day"
                        },
                        new
                        {
                            SpeakerId = "370b9c45-b10e-4e4e-affc-b998344235ad",
                            FirstName = "John",
                            LastName = "Fox"
                        },
                        new
                        {
                            SpeakerId = "5d00b14b-a2b8-4e4e-8e7e-10a2894620f0",
                            FirstName = "Art",
                            LastName = "Ash"
                        },
                        new
                        {
                            SpeakerId = "f4c34bef-0554-4956-9e0c-64de17b38cfd",
                            FirstName = "Mia",
                            LastName = "Hay"
                        },
                        new
                        {
                            SpeakerId = "a66c009d-470b-4b7d-befd-364d2eb439ac",
                            FirstName = "Xam",
                            LastName = "Xyllene"
                        },
                        new
                        {
                            SpeakerId = "10ca9081-1f3b-4500-96d1-bc7fe97be6cd",
                            FirstName = "Brock",
                            LastName = "Nguyen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
