// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerAPI.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20200317001312_M5")]
    partial class M5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2Library.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "88e69f5b-7d87-4d38-b29a-60dffbe0f78c",
                            FirstName = "Tom",
                            LastName = "Day"
                        },
                        new
                        {
                            SpeakerId = "5404cb88-d41d-4202-b65d-bef8a200fb6c",
                            FirstName = "John",
                            LastName = "Fox"
                        },
                        new
                        {
                            SpeakerId = "55d49db9-93d6-4cd7-b6db-f8ef75221ea1",
                            FirstName = "Art",
                            LastName = "Ash"
                        },
                        new
                        {
                            SpeakerId = "2cd1857a-024e-46e1-ae01-2fdca1654dfc",
                            FirstName = "Mia",
                            LastName = "Hay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
